import json

examples = [
    # LOOKUP
    {"text": "Which products contain CAS 75-07-0?",                    "label": "lookup"},
    {"text": "What products have acetaldehyde?",                        "label": "lookup"},
    {"text": "Find products with CAS 13463-67-7",                       "label": "lookup"},
    {"text": "Products containing titanium dioxide",                    "label": "lookup"},
    {"text": "What contains formaldehyde?",                             "label": "lookup"},
    {"text": "Show me products with carbon black",                      "label": "lookup"},
    {"text": "Which items contain retinol?",                            "label": "lookup"},
    {"text": "Products that contain talc",                              "label": "lookup"},
    {"text": "Find all products with silica",                           "label": "lookup"},
    {"text": "What products have CAS 1333-86-4?",                      "label": "lookup"},
    {"text": "Show products containing parabens",                       "label": "lookup"},
    {"text": "Which cosmetics contain triclosan?",                      "label": "lookup"},
    {"text": "What items contain CAS 50-00-0?",                        "label": "lookup"},
    {"text": "Products with titanium dioxide in them",                  "label": "lookup"},
    {"text": "Which products have carbon black?",                       "label": "lookup"},
    {"text": "Show items containing talc",                              "label": "lookup"},
    {"text": "What cosmetics contain retinol?",                         "label": "lookup"},
    {"text": "Find products that have formaldehyde",                    "label": "lookup"},
    {"text": "Products with CAS number 75-07-0",                       "label": "lookup"},
    {"text": "Which brands contain acetaldehyde?",                      "label": "lookup"},
    {"text": "Items containing CAS 13463-67-7",                        "label": "lookup"},
    {"text": "What has silica in it?",                                  "label": "lookup"},
    {"text": "Products that have parabens",                             "label": "lookup"},
    {"text": "Which products contain bismuth?",                         "label": "lookup"},
    {"text": "Show me what contains mica",                              "label": "lookup"},
    {"text": "Find products with glycerin",                             "label": "lookup"},
    {"text": "What products include lanolin?",                          "label": "lookup"},

    # LIST
    {"text": "List all chemicals reported by Revlon",                   "label": "list"},
    {"text": "Show all products from Avon",                             "label": "list"},
    {"text": "Give me all chemicals for Maybelline",                    "label": "list"},
    {"text": "Find all discontinued products",                          "label": "list"},
    {"text": "List every product in hair care",                         "label": "list"},
    {"text": "Show all records for Elizabeth Arden",                    "label": "list"},
    {"text": "Give me every chemical for Colgate",                      "label": "list"},
    {"text": "List all brands that reported chemicals",                 "label": "list"},
    {"text": "Show me all products from L'Oreal",                       "label": "list"},
    {"text": "Find all active products",                                "label": "list"},
    {"text": "List all products in skin care category",                 "label": "list"},
    {"text": "Show every record for Regis Corporation",                 "label": "list"},
    {"text": "List all chemicals for Avon",                             "label": "list"},
    {"text": "Show all discontinued products from Revlon",              "label": "list"},
    {"text": "Give me every product from Elizabeth Arden",              "label": "list"},
    {"text": "Find all chemicals reported in hair care",                "label": "list"},
    {"text": "List every brand under makeup category",                  "label": "list"},
    {"text": "Show all records from 2018",                              "label": "list"},
    {"text": "Give me all products from Colgate Palmolive",             "label": "list"},
    {"text": "List all chemicals for La Prairie",                       "label": "list"},
    {"text": "Show every discontinued product",                         "label": "list"},
    {"text": "Find all products in nail care",                          "label": "list"},
    {"text": "List all chemicals in the database",                      "label": "list"},
    {"text": "Show all companies that reported chemicals",              "label": "list"},
    {"text": "Give me all records for skin care",                       "label": "list"},
    {"text": "List every product reported by Maybelline",               "label": "list"},
    {"text": "Show all active products from Avon",                      "label": "list"},

    # COMPARE
    {"text": "Compare Revlon and Avon disclosures",                     "label": "compare"},
    {"text": "Difference between Revlon and L'Oreal",                   "label": "compare"},
    {"text": "Revlon vs Avon chemical reports",                         "label": "compare"},
    {"text": "How does Avon compare to Revlon?",                        "label": "compare"},
    {"text": "Contrast hair care vs skin care chemicals",               "label": "compare"},
    {"text": "Compare Elizabeth Arden and Avon",                        "label": "compare"},
    {"text": "Side by side comparison of Revlon and Maybelline",        "label": "compare"},
    {"text": "What is the difference between Avon and Colgate?",        "label": "compare"},
    {"text": "Compare chemicals in makeup vs hair care",                "label": "compare"},
    {"text": "Revlon versus Maybelline chemical disclosures",           "label": "compare"},
    {"text": "How do Avon and L'Oreal differ?",                         "label": "compare"},
    {"text": "Compare Colgate and Revlon reports",                      "label": "compare"},
    {"text": "Contrast Avon vs Elizabeth Arden",                        "label": "compare"},
    {"text": "Which company reports more chemicals Revlon or Avon?",    "label": "compare"},
    {"text": "Compare hair care and nail care disclosures",             "label": "compare"},
    {"text": "Difference in chemicals between Maybelline and L'Oreal",  "label": "compare"},
    {"text": "Side by side Avon and Colgate",                           "label": "compare"},
    {"text": "Compare makeup and skin care chemical counts",            "label": "compare"},
    # SUMMARIZE
    {"text": "Summarize chemicals reported by Avon",                    "label": "summarize"},
    {"text": "Give me an overview of Revlon disclosures",               "label": "summarize"},
    {"text": "What chemicals does Elizabeth Arden report?",             "label": "summarize"},
    {"text": "Tell me about Colgate Palmolive chemicals",               "label": "summarize"},
    {"text": "Overview of chemicals in makeup products",                "label": "summarize"},
    {"text": "Summarize what Maybelline has reported",                  "label": "summarize"},
    {"text": "Give a summary of chemicals for hair care",               "label": "summarize"},
    {"text": "What does Avon report?",                                  "label": "summarize"},
    {"text": "Describe the chemicals reported by Revlon",               "label": "summarize"},
    {"text": "Give me an idea of what L'Oreal reports",                 "label": "summarize"},
    {"text": "Summarize Avon chemical disclosures",                     "label": "summarize"},
    {"text": "What is the chemical profile of Revlon?",                 "label": "summarize"},
    {"text": "Give overview of Elizabeth Arden reports",                "label": "summarize"},
    {"text": "Summarize all chemicals in skin care",                    "label": "summarize"},
    {"text": "Tell me about chemicals in hair care products",           "label": "summarize"},
    {"text": "What chemicals are commonly reported?",                   "label": "summarize"},
    {"text": "Give me a summary of Colgate disclosures",                "label": "summarize"},
    {"text": "Overview of what Maybelline reports",                     "label": "summarize"},
    {"text": "Summarize chemical reporting for nail care",              "label": "summarize"},
    {"text": "What does La Prairie report?",                            "label": "summarize"},

    # TREND
    {"text": "Show reporting trends since 2017",                        "label": "trend"},
    {"text": "How many reports were filed per year?",                   "label": "trend"},
    {"text": "Chemical reporting history for Revlon",                   "label": "trend"},
    {"text": "Trend analysis for hair care category",                   "label": "trend"},
    {"text": "How have disclosures changed over time?",                 "label": "trend"},
    {"text": "Show me year by year reporting for Avon",                 "label": "trend"},
    {"text": "Reporting trends for skin care since 2018",               "label": "trend"},
    {"text": "How many chemicals were added annually?",                 "label": "trend"},
    {"text": "Show growth in chemical disclosures over time",           "label": "trend"},
    {"text": "Year wise reporting for Elizabeth Arden",                 "label": "trend"},
    {"text": "Trend in chemical reporting since 2017",                  "label": "trend"},
    {"text": "How has Revlon reporting changed over the years?",        "label": "trend"},
    {"text": "Show annual chemical disclosure trends",                  "label": "trend"},
    {"text": "Year over year reporting for Avon",                       "label": "trend"},
    {"text": "How many products were reported each year?",              "label": "trend"},
    {"text": "Show reporting history for makeup category",              "label": "trend"},
    {"text": "Trend analysis since 2018",                               "label": "trend"},
    {"text": "How have chemical disclosures grown annually?",           "label": "trend"},
    {"text": "Show me the reporting trend for hair care",               "label": "trend"},
    {"text": "Chemical disclosure history by year",                     "label": "trend"},

# LIST vs SUMMARIZE disambiguation
    {"text": "List all chemicals reported by Revlon",                   "label": "list"},
    {"text": "List all chemicals reported by Avon",                     "label": "list"},
    {"text": "List all chemicals reported by Maybelline",               "label": "list"},
    {"text": "List all chemicals reported by L'Oreal",                  "label": "list"},
    {"text": "List all chemicals reported by Colgate",                  "label": "list"},
    {"text": "List all products reported by Revlon",                    "label": "list"},
    {"text": "List all products reported by Avon",                      "label": "list"},
    {"text": "List all records for Revlon",                             "label": "list"},
    {"text": "List all records for Avon",                               "label": "list"},
    {"text": "Show all chemicals for Revlon",                           "label": "list"},
    {"text": "Show all chemicals for Avon",                             "label": "list"},
    {"text": "Show all chemicals for Maybelline",                       "label": "list"},
    {"text": "Give all chemicals for Revlon",                           "label": "list"},
    {"text": "Give all products for Avon",                              "label": "list"},

    # SUMMARIZE vs LIST disambiguation
    {"text": "Summarize Revlon chemical disclosures",                   "label": "summarize"},
    {"text": "Summarize Avon chemical disclosures",                     "label": "summarize"},
    {"text": "Summarize Maybelline chemical disclosures",               "label": "summarize"},
    {"text": "Give a summary for Revlon",                               "label": "summarize"},
    {"text": "Give a summary for Avon",                                 "label": "summarize"},
    {"text": "Overview of Revlon chemicals",                            "label": "summarize"},
    {"text": "Overview of Avon chemicals",                              "label": "summarize"},

    # LOOKUP vs LIST disambiguation
    {"text": "Which products contain acetaldehyde?",                    "label": "lookup"},
    {"text": "Which products contain carbon black?",                    "label": "lookup"},
    {"text": "Which products contain titanium dioxide?",                "label": "lookup"},
    {"text": "What products have talc?",                                "label": "lookup"},
    {"text": "What products have silica?",                              "label": "lookup"},
    {"text": "Find products containing mica",                           "label": "lookup"},
    {"text": "Find products containing glycerin",                       "label": "lookup"},

    # QUALITY
    {"text": "Are there products with missing CAS numbers?",            "label": "quality"},
    {"text": "Find records with null chemical names",                   "label": "quality"},
    {"text": "Show me data quality issues",                             "label": "quality"},
    {"text": "Which records have conflicting dates?",                   "label": "quality"},
    {"text": "Find products without a CAS number",                      "label": "quality"},
    {"text": "Are there any incomplete records?",                       "label": "quality"},
    {"text": "Show records with missing data",                          "label": "quality"},
    {"text": "Find entries with no chemical name",                      "label": "quality"},
    {"text": "Which products have data errors?",                        "label": "quality"},
    {"text": "Show me records with invalid dates",                      "label": "quality"},
    {"text": "Find all records with null CAS numbers",                  "label": "quality"},
    {"text": "Show products with missing chemical information",         "label": "quality"},
    {"text": "Which records are incomplete?",                           "label": "quality"},
    {"text": "Find data quality problems in the dataset",               "label": "quality"},
    {"text": "Show me entries with no CAS number",                      "label": "quality"},
    {"text": "Are there records with conflicting information?",         "label": "quality"},
    {"text": "Find all missing or null values",                         "label": "quality"},
    {"text": "Which products have no chemical name?",                   "label": "quality"},
    {"text": "Show data issues in the database",                        "label": "quality"},
    {"text": "Find records where CAS number is empty",                  "label": "quality"},
    {"text": "Which entries have invalid discontinuation dates?",       "label": "quality"},
    {"text": "Show me all records with errors",                         "label": "quality"},

    # More LIST examples with "reported by" pattern
    {"text": "List all chemicals reported by Elizabeth Arden",          "label": "list"},
    {"text": "List all chemicals reported by La Prairie",               "label": "list"},
    {"text": "List all chemicals reported by Regis Corporation",        "label": "list"},
    {"text": "List all chemicals reported by Colgate Palmolive",        "label": "list"},
    {"text": "Show all chemicals reported by Revlon",                   "label": "list"},
    {"text": "Show all chemicals reported by Avon",                     "label": "list"},
    {"text": "Show all chemicals reported by Maybelline",               "label": "list"},
    {"text": "Give me all chemicals reported by L'Oreal",               "label": "list"},
    {"text": "Give me all chemicals reported by Elizabeth Arden",       "label": "list"},
    {"text": "Find all chemicals reported by Colgate",                  "label": "list"},
    {"text": "Find all chemicals reported by La Prairie",               "label": "list"},
    {"text": "List chemicals by Revlon",                                "label": "list"},
    {"text": "List chemicals by Avon",                                  "label": "list"},
    {"text": "List chemicals by Maybelline",                            "label": "list"},
    {"text": "List products by Revlon",                                 "label": "list"},
    {"text": "List products by Avon",                                   "label": "list"},

    # More LOOKUP examples with "contain/contains" pattern
    {"text": "Which products contain CAS 75-07-0",                     "label": "lookup"},
    {"text": "Which products contain CAS 1333-86-4",                   "label": "lookup"},
    {"text": "Which products contain CAS 13463-67-7",                  "label": "lookup"},
    {"text": "Which products contain CAS 50-00-0",                     "label": "lookup"},
    {"text": "Products that contain acetaldehyde",                      "label": "lookup"},
    {"text": "Products that contain carbon black",                      "label": "lookup"},
    {"text": "Products that contain titanium dioxide",                  "label": "lookup"},
    {"text": "Products that contain talc",                              "label": "lookup"},
    {"text": "Products that contain silica",                            "label": "lookup"},
    {"text": "Products that contain mica",                              "label": "lookup"},
    {"text": "Show products that contain formaldehyde",                 "label": "lookup"},
    {"text": "Show products that contain retinol",                      "label": "lookup"},
    {"text": "Find products that contain parabens",                     "label": "lookup"},
    {"text": "Find products that contain triclosan",                    "label": "lookup"},
    {"text": "What products contain acetaldehyde",                      "label": "lookup"},
    {"text": "What products contain carbon black",                      "label": "lookup"},

    # COMPARE — needs more examples (only 18)
    {"text": "Compare Avon and Maybelline chemical reports",            "label": "compare"},
    {"text": "Revlon vs L'Oreal disclosures",                          "label": "compare"},
    {"text": "Difference between Avon and Maybelline",                  "label": "compare"},
    {"text": "How does Revlon compare to Colgate?",                     "label": "compare"},
    {"text": "Compare La Prairie and Elizabeth Arden",                  "label": "compare"},
    {"text": "Contrast Revlon vs Colgate chemical reports",             "label": "compare"},
    {"text": "Maybelline versus L'Oreal disclosures",                   "label": "compare"},
    {"text": "Side by side Avon and Revlon",                            "label": "compare"},
    {"text": "Compare nail care and makeup categories",                 "label": "compare"},
    {"text": "Difference between skin care and hair care chemicals",    "label": "compare"},

    # QUALITY — needs more examples (only 22)
    {"text": "Show products where CAS number is null",                  "label": "quality"},
    {"text": "Find rows with empty chemical names",                     "label": "quality"},
    {"text": "Which records have no CAS number assigned?",              "label": "quality"},
    {"text": "Show me all null values in the dataset",                  "label": "quality"},
    {"text": "Find products with missing information",                  "label": "quality"},
    {"text": "Are there entries without chemical names?",               "label": "quality"},
    {"text": "Show records where data is incomplete",                   "label": "quality"},
    {"text": "Find all rows with missing CAS",                          "label": "quality"},
    {"text": "Which products are missing chemical data?",               "label": "quality"},
    {"text": "Show data errors and inconsistencies",                    "label": "quality"},

    # SUMMARIZE — better distinguish from LIST
    {"text": "What is a summary of Avon chemicals?",                    "label": "summarize"},
    {"text": "Give me a brief overview of Revlon",                      "label": "summarize"},
    {"text": "Summarize the top chemicals for Maybelline",              "label": "summarize"},
    {"text": "What are the key chemicals reported by Avon?",            "label": "summarize"},
    {"text": "Give me a high level view of Revlon disclosures",         "label": "summarize"},
    {"text": "What is the chemical summary for Elizabeth Arden?",       "label": "summarize"},
    {"text": "Briefly describe what Colgate reports",                   "label": "summarize"},
    {"text": "Give me key highlights of Avon chemical reports",         "label": "summarize"},
    {"text": "What are the main chemicals for L'Oreal?",                "label": "summarize"},
    {"text": "Provide an overview of La Prairie disclosures",           "label": "summarize"},

    # TREND — needs more examples
    {"text": "Show chemical reporting trends by year",                  "label": "trend"},
    {"text": "How did reporting change from 2017 to 2019?",             "label": "trend"},
    {"text": "Annual trend of chemical disclosures",                    "label": "trend"},
    {"text": "Show me year wise chemical reporting",                    "label": "trend"},
    {"text": "How many chemicals were reported each year?",             "label": "trend"},
    {"text": "Trend of Revlon reporting over the years",                "label": "trend"},
    {"text": "Show reporting growth since 2017",                        "label": "trend"},
    {"text": "Year by year chemical disclosure data",                   "label": "trend"},
    {"text": "How has the number of reports changed annually?",         "label": "trend"},
    {"text": "Show me reporting statistics by year",                    "label": "trend"},

    # LIST — "reported by" pattern is the key signal
    {"text": "List all chemicals reported by Revlon",                   "label": "list"},
    {"text": "List chemicals reported by Avon",                         "label": "list"},
    {"text": "List chemicals reported by Maybelline",                   "label": "list"},
    {"text": "List chemicals reported by L'Oreal",                      "label": "list"},
    {"text": "List chemicals reported by Colgate",                      "label": "list"},
    {"text": "List chemicals reported by La Prairie",                   "label": "list"},
    {"text": "List chemicals reported by Elizabeth Arden",              "label": "list"},
    {"text": "Show chemicals reported by Revlon",                       "label": "list"},
    {"text": "Show chemicals reported by Avon",                         "label": "list"},
    {"text": "Show chemicals reported by Maybelline",                   "label": "list"},
    {"text": "Get chemicals reported by Revlon",                        "label": "list"},
    {"text": "Get chemicals reported by Avon",                          "label": "list"},
    {"text": "Fetch all chemicals reported by Colgate",                 "label": "list"},
    {"text": "Pull all chemicals reported by L'Oreal",                  "label": "list"},

    # SUMMARIZE — "what does X report" is the key signal
    {"text": "What chemicals does Revlon report?",                      "label": "summarize"},
    {"text": "What chemicals does Avon report?",                        "label": "summarize"},
    {"text": "What chemicals does Maybelline report?",                  "label": "summarize"},
    {"text": "What chemicals does L'Oreal report?",                     "label": "summarize"},
    {"text": "What chemicals does Colgate report?",                     "label": "summarize"},
    {"text": "What chemicals does Elizabeth Arden report?",             "label": "summarize"},
    {"text": "What does Revlon report chemically?",                     "label": "summarize"},
    {"text": "What does Avon disclose?",                                "label": "summarize"},
    {"text": "What has Maybelline reported overall?",                   "label": "summarize"},
    {"text": "What chemical profile does Revlon have?",                 "label": "summarize"},
    {"text": "Summarise Avon",                                          "label": "summarize"},
    {"text": "Summarise Revlon",                                        "label": "summarize"},
    {"text": "Summarise Maybelline",                                    "label": "summarize"},
    {"text": "Summarise L'Oreal",                                       "label": "summarize"},
]



with open("training_data.json", "w") as f:
    json.dump(examples, f, indent=2)

print(f"Saved {len(examples)} training examples")
from collections import Counter
labels = [e["label"] for e in examples]
for k, v in Counter(labels).items():
    print(f"  {k}: {v}")